In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3387, 4007, 4033, 3116],
 [3387, 4007, 4033, 9685],
 [3387, 2078, 4033, 7489],
 [4062, 810, 8334, 2991, 4207],
 [4062, 810, 8334, 2991, 2141],
 [1030, 3387, 2993, 4033, 6962],
 [2627, 1549, 2571, 2991]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3387 4007 4033 3116]
 [   0    0    0    0 3387 4007 4033 9685]
 [   0    0    0    0 3387 2078 4033 7489]
 [   0    0    0 4062  810 8334 2991 4207]
 [   0    0    0 4062  810 8334 2991 2141]
 [   0    0    0 1030 3387 2993 4033 6962]
 [   0    0    0    0 2627 1549 2571 2991]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

d:\AI ML\.venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step


array([[[ 0.00849031, -0.02530506, -0.00684624,  0.01385058,
          0.00643094, -0.04114116,  0.04225173,  0.00982051,
          0.04046145, -0.00273896],
        [ 0.00849031, -0.02530506, -0.00684624,  0.01385058,
          0.00643094, -0.04114116,  0.04225173,  0.00982051,
          0.04046145, -0.00273896],
        [ 0.00849031, -0.02530506, -0.00684624,  0.01385058,
          0.00643094, -0.04114116,  0.04225173,  0.00982051,
          0.04046145, -0.00273896],
        [ 0.00849031, -0.02530506, -0.00684624,  0.01385058,
          0.00643094, -0.04114116,  0.04225173,  0.00982051,
          0.04046145, -0.00273896],
        [ 0.01475639,  0.04241253, -0.01564729,  0.03035435,
          0.01208197,  0.04949958, -0.03921928,  0.03786978,
         -0.00525435, -0.04160945],
        [ 0.04483775, -0.04728469,  0.04151083, -0.04850792,
         -0.01564585,  0.01225663, -0.01206829, -0.04869201,
          0.0262571 ,  0.0416904 ],
        [ 0.01067474, -0.02804014,  0.02830965, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 3387, 4007, 4033, 3116], dtype=int32)

In [15]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>